### ISSUE TITLE
Windows stay black if ra25 is left open for a while

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#15]
This may be a gi bug or an emergent bug.  Not sure.

I had the ra25 example open today since this morning on my Mac under Mojave.  When I went back to it just now the windows were totally black and stayed black, unless I went full screen. But then when I left full screen mode, it gave me really distorted text.

I am using an LG large screen monitor with new MacBook Pro.  

Maybe related,  I noticed that sometimes on the large screen monitor the window will rescale to be several times wider than the screen.  I have to drag the right edge back to get it scaled to the proper size

**Comment by rcoreilly** [comment]
this should be fixed with a new release of glfw 3.3. I might just have to get our own fork for other reasons and do this sooner but hopefully avail soon.

**Comment by rcoreilly** [comment]
some of this might be fixed with very latest changes in goki/gi, which require a go get -u ./... (new go-gl/glfw package) -- there are still some issues in that package when there are no monitors -- the opengl context seems to disappear and then we have to essentially restart anyway.  maybe a way to fix it but will take more work.

**Comment by rcoreilly** [comment]
assuming fixed -- reopen if not.
