### ISSUE TITLE
Netview window continually expands in width

### ISSUE THREAD

**Issue by StephenJRead** [emer/emergent#45]
If I leave a project open for several days, it will gradually get wider and wider to the point where it is several multiples wider.  Both the Control panel window on the left and the Neview panel on the right continue to get wider.  The height does not change much, if at all during the same time frame.

**Comment by rcoreilly** [comment]
If you update to latest glfw and associated goki/gi etc (i.e., do a full go get -u ./... in leabra/examples/ra25) does this still happen?  I have not been having any weirdness in the windows after the display sleeps etc, since the new glfw version.  And several of these tickets are pretty much the same underlying bug so if this is fixed, we can close several of them.

**Comment by StephenJRead** [comment]
I’ll check it out.  Any idea whether this might help the problem with wonky displays on some external monitors?


On Mar 10, 2020, at 2:13 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


If you update to latest glfw and associated goki/gi etc (i.e., do a full go get -u ./... in leabra/examples/ra25) does this still happen? I have not been having any weirdness in the windows after the display sleeps etc, since the new glfw version. And several of these tickets are pretty much the same underlying bug so if this is fixed, we can close several of them.

**Comment by rcoreilly** [comment]
I'm guessing this is now fixed -- reopen if not..
